### ISSUE TITLE
Which version of CEF if used?

### ISSUE THREAD

**Issue by korobochka** [DerelictOrg/DerelictCEF#3]
Hello, please advice which CEF version was used to build this?

I found some differences while trying to build this on Linux with `cef_binary_3.2171.1979_linux64`.

For example, window info is defined as:

```
typedef struct _cef_window_info_t {
  unsigned int x;
  unsigned int y;
  unsigned int width;
  unsigned int height;

  cef_window_handle_t parent_window;

  int windowless_rendering_enabled;

  int transparent_painting_enabled;

  cef_window_handle_t window;
} cef_window_info_t;
```

First 4 parameters seem to be missing in the bindings.

Also, function `cef_end_tracing_async` is not available in the library, so I had to comment it out in `cef.d`.

**Comment by korobochka** [comment]
Also your example(dpaste from the blog post) fails with message

```
*** Error in `./cef': free(): invalid pointer: 0x00000d1bce3dd000 ***
```

but this may be due to my poor understanding of CEF.
Paste here, but I don't think it helps: https://gist.github.com/Korobochka/0db20eaa14f0c6848800

**Comment by mdparker** [comment]
According to the README in my copy of the CEF source, it's version 3.1750.1738. I'm afraid my understanding of CEF is quite limited at the moment. I haven't yet taken the time to get too intimate with it, so you probably know as much or more about it than I do. The example code was adapted from https://github.com/CzarekTomczak/cefcapi, as it's the only thing I was able to find that was anywhere close to being up-to-date. Time is extremely tight for me right now, but I'll keep this open until I can look into it if no one else gets to it first.
