### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by kniteli** [DerelictOrg/DerelictCEF#4]
I'm getting a compiler error on this lib (I'm using dub):

Performing "debug" build using dmd for x86_64.
derelict-util 2.0.4: target for configuration "library" is up to date.
derelict-cef 0.0.2: building configuration "library"...
../../../.dub/packages/derelict-cef-0.0.2/source/derelict/cef/types.d(738,19): Error: undefined identifier 'Derleict_OS_Linux', did you mean variable 'Derelict_OS_Linux'?
../../../.dub/packages/derelict-cef-0.0.2/source/derelict/cef/types.d(750,19): Error: undefined identifier 'Derleict_OS_Mac', did you mean variable 'Derelict_OS_Mac'?
../../../.dub/packages/derelict-cef-0.0.2/source/derelict/cef/types.d(855,120): Error: undefined identifier 'cef_window_info_t'
../../../.dub/packages/derelict-cef-0.0.2/source/derelict/cef/types.d(1260,218): Error: undefined identifier 'cef_window_info_t'
../../../.dub/packages/derelict-cef-0.0.2/source/derelict/cef/functions.d(154,5): Error: undefined identifier 'cef_main_args_t'
../../../.dub/packages/derelict-cef-0.0.2/source/derelict/cef/functions.d(155,5): Error: undefined identifier 'cef_main_args_t'
../../../.dub/packages/derelict-cef-0.0.2/source/derelict/cef/functions.d(162,5): Error: undefined identifier 'cef_window_info_t'
../../../.dub/packages/derelict-cef-0.0.2/source/derelict/cef/functions.d(163,5): Error: undefined identifier 'cef_window_info_t'
dmd failed with exit code 1.

Is this a configuration error on my end? It's a bare program, basically just a dub init.

**Comment by kniteli** [comment]
Ok, if I clone this repo and then point dub to it directly with eg

dependency "derelict-cef" path="../../DerelictCEF"

it works fine, not sure what's going wrong with pulling it down

**Comment by mdparker** [comment]
The problem was that after merging the last pull request that fixed the issues you were seeing, I never pulled the changes down to my local copy. When I later tagged a new release, it was for a commit prior to the fixes and that's what you were getting with DUB. I've tagged a new 0.0.3 release on the proper commit now, so DUB should give you the current HEAD now.
